# Generated by Django 3.2.8 on 2021-10-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('img', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('company', models.CharField(max_length=150)),
                ('info', models.CharField(max_length=250)),
                ('inCart', models.BooleanField(default=False)),
            ],
        ),
    ]
